name: Deploy API Descida da Ladeira

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositório
        uses: actions/checkout@v3

      - name: Configurando SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configurando variáveis de ambiente AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configurando versão do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Limpando cache e removendo pastas desnecessárias
        run: |
          npm cache clean --force
          rm -rf build node_modules package-lock.json

      - name: Instalando dependências
        run: npm install

      - name: Build com AWS SAM
        run: sam build --use-container

      - name: Deploy
        run: |
          sam deploy \
          --template-file template.yaml \
          --stack-name api-descida-da-ladeira-prod \
          --s3-bucket "${{ secrets.S3_BUCKET }}" \
          --capabilities CAPABILITY_IAM \
          --region us-east-1 \
          --no-fail-on-empty-changeset \
          --parameter-overrides \
          ParameterKey=NodeEnv,ParameterValue=producao \
          ParameterKey=MongoUriProd,ParameterValue=${{ secrets.MONGODB_URI_PROD }} \
          ParameterKey=JwtSecret,ParameterValue=${{ secrets.JWT_SECRET }} \
          ParameterKey=AwsAccessKeyId,ParameterValue=${{ secrets.AWS_ACCESS_KEY_ID }} \
          ParameterKey=AwsSecretAccessKey,ParameterValue=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          ParameterKey=AwsBucketName,ParameterValue=${{ secrets.AWS_BUCKET_NAME_URL_ASSINADA }} \
          ParameterKey=AwsRegion,ParameterValue=us-east-1
    env:
      PORTA: 0
      NODE_ENV: producao
